2018-04-08 14:07:25 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:07:47 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:08:38 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:10:13 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:10:51 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:11:41 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:11:56 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:13:21 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:14:13 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:18:43 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:18:56 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:20:16 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:20:39 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:21:48 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:23:05 yii\base\InvalidRouteException: Unable to resolve the request "favicon.ico". in E:\project\backend\vendor\yiisoft\yii2\base\Module.php:537
Stack trace:
#0 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('favicon.ico', Array)
#1 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 E:\project\backend\public\index.php(20): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: 页面未找到。 in E:\project\backend\vendor\yiisoft\yii2\web\Application.php:115
Stack trace:
#0 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 E:\project\backend\public\index.php(20): yii\base\Application->run()
#2 {main}
2018-04-08 14:23:06 yii\base\InvalidRouteException: Unable to resolve the request "favicon.ico". in E:\project\backend\vendor\yiisoft\yii2\base\Module.php:537
Stack trace:
#0 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('favicon.ico', Array)
#1 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 E:\project\backend\public\index.php(20): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: 页面未找到。 in E:\project\backend\vendor\yiisoft\yii2\web\Application.php:115
Stack trace:
#0 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 E:\project\backend\public\index.php(20): yii\base\Application->run()
#2 {main}
2018-04-08 14:24:12 yii\base\InvalidRouteException: Unable to resolve the request "favicon.ico". in E:\project\backend\vendor\yiisoft\yii2\base\Module.php:537
Stack trace:
#0 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('favicon.ico', Array)
#1 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 E:\project\backend\public\index.php(20): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: 页面未找到。 in E:\project\backend\vendor\yiisoft\yii2\web\Application.php:115
Stack trace:
#0 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 E:\project\backend\public\index.php(20): yii\base\Application->run()
#2 {main}
2018-04-08 14:24:31 yii\base\InvalidRouteException: Unable to resolve the request "favicon.ico". in E:\project\backend\vendor\yiisoft\yii2\base\Module.php:537
Stack trace:
#0 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('favicon.ico', Array)
#1 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 E:\project\backend\public\index.php(20): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: 页面未找到。 in E:\project\backend\vendor\yiisoft\yii2\web\Application.php:115
Stack trace:
#0 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 E:\project\backend\public\index.php(20): yii\base\Application->run()
#2 {main}
2018-04-08 14:24:41 yii\base\InvalidRouteException: Unable to resolve the request "favicon.ico". in E:\project\backend\vendor\yiisoft\yii2\base\Module.php:537
Stack trace:
#0 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('favicon.ico', Array)
#1 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 E:\project\backend\public\index.php(20): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: 页面未找到。 in E:\project\backend\vendor\yiisoft\yii2\web\Application.php:115
Stack trace:
#0 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 E:\project\backend\public\index.php(20): yii\base\Application->run()
#2 {main}
2018-04-08 14:24:49 yii\base\InvalidRouteException: Unable to resolve the request "favicon.ico". in E:\project\backend\vendor\yiisoft\yii2\base\Module.php:537
Stack trace:
#0 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('favicon.ico', Array)
#1 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 E:\project\backend\public\index.php(20): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: 页面未找到。 in E:\project\backend\vendor\yiisoft\yii2\web\Application.php:115
Stack trace:
#0 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 E:\project\backend\public\index.php(20): yii\base\Application->run()
#2 {main}
2018-04-08 14:25:12 yii\base\InvalidRouteException: Unable to resolve the request "favicon.ico". in E:\project\backend\vendor\yiisoft\yii2\base\Module.php:537
Stack trace:
#0 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('favicon.ico', Array)
#1 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 E:\project\backend\public\index.php(20): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: 页面未找到。 in E:\project\backend\vendor\yiisoft\yii2\web\Application.php:115
Stack trace:
#0 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 E:\project\backend\public\index.php(20): yii\base\Application->run()
#2 {main}
2018-04-08 14:40:40 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:41:59 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:42:46 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:51:58 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
2018-04-08 14:52:34 Backend\Exception\CustomException: 签名错误 in E:\project\backend\backend\behavior\VerifySign.php:40
Stack trace:
#0 [internal function]: Backend\behavior\VerifySign->verifySignature()
#1 E:\project\backend\vendor\yiisoft\yii2\base\Component.php(297): call_user_func_array(Array, Array)
#2 E:\project\backend\backend\modules\common\controllers\BusinessController.php(77): yii\base\Component->__call('verifySignature', Array)
#3 E:\project\backend\vendor\yiisoft\yii2\base\Controller.php(155): Backend\modules\common\controllers\BusinessController->beforeAction(Object(yii\rest\UpdateAction))
#4 E:\project\backend\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('update', Array)
#5 E:\project\backend\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('admin/admin-use...', Array)
#6 E:\project\backend\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\project\backend\public\index.php(20): yii\base\Application->run()
#8 {main}
